#!/usr/bin/env bash

set -euo pipefail

TARGET_FILE="apps/web/.env.local"

if [ ! -f ".env" ]; then
  echo "[sync-web-env] root .env not found, skipping frontend env sync"
  exit 0
fi

{
  echo "# Auto-generated from repo root .env"
  echo "# Do not edit this file directly; update /.env instead."
  grep -E '^NEXT_PUBLIC_[A-Z0-9_]+=.*$' .env || true
} > "$TARGET_FILE"

echo "[sync-web-env] wrote $TARGET_FILE"
